---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample
  labels:
    app: sample
  annotations:
    dapr.io/enabled: "true"
    dapr.io/config: accesscontrol-sample
    dapr.io/app-id: sample
    dapr.io/enable-api-logging: 'true'
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: sample
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sample
      annotations:
        dapr.io/app-port: '8080'
        dapr.io/enabled: "true"
        dapr.io/config: accesscontrol-sample
        dapr.io/app-id: sample
        dapr.io/enable-api-logging: 'true'
    spec:
      hostAliases:
      - ip: 10.233.41.235
        hostnames:
        - auth.tache.ai
      imagePullSecrets:
      - name: zot-pull-secret
      containers:
      - name: sample
        image: registry.hexalith.com/sample:0.0.0-preview.0.505
        imagePullPolicy: IfNotPresent
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 10
          timeoutSeconds: 10
          periodSeconds: 10
          failureThreshold: 30
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 120
          timeoutSeconds: 10
          periodSeconds: 10
          failureThreshold: 30
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        envFrom:
        - configMapRef:
            name: sample-env
      terminationGracePeriodSeconds: 180