namespace: hexalith-parties

resources:
- eventstore
- eventstore-admin
- eventstore-admin-ui
- parties
- parties-mcp
- tenants
- redis
- memories
- keycloak
- namespace.yaml

generatorOptions:
  disableNameSuffixHash: true
