namespace: hexalith-parties

resources:
- eventstore
- eventstore-admin
- eventstore-admin-ui
- parties
- parties-mcp
- tenants
- redis
- memories
- namespace.yaml

- keycloak
generatorOptions:
  disableNameSuffixHash: true


