---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventstore-admin
  labels:
    app: eventstore-admin
  annotations:
    dapr.io/enabled: "true"
    dapr.io/config: accesscontrol-eventstore-admin
    dapr.io/app-id: eventstore-admin
    dapr.io/app-port: '8080'
    dapr.io/enable-api-logging: 'true'
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: eventstore-admin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: eventstore-admin
      annotations:
        dapr.io/enabled: "true"
        dapr.io/config: accesscontrol-eventstore-admin
        dapr.io/app-id: eventstore-admin
        dapr.io/app-port: '8080'
        dapr.io/enable-api-logging: 'true'
    spec:
      imagePullSecrets:
      - name: zot-pull-secret
      containers:
      - name: eventstore-admin
        image: registry.hexalith.com/eventstore-admin:0.0.0-preview.0.506
        imagePullPolicy: IfNotPresent
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 10
          timeoutSeconds: 10
          periodSeconds: 10
          failureThreshold: 30
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 120
          timeoutSeconds: 10
          periodSeconds: 10
          failureThreshold: 30
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        envFrom:
        - configMapRef:
            name: eventstore-admin-env
      terminationGracePeriodSeconds: 180