resources:
- deployment.yaml
- service.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: eventstore-admin-env
  literals:
    - OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY=in_memory
    - ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
    - HTTP_PORTS=8080
    - EVENTSTORE_HTTP=http://eventstore:8080
    - services__eventstore__http__0=http://eventstore:8080
    - ASPNETCORE_ENVIRONMENT=Development
    - DOTNET_ENVIRONMENT=Development
    - Authentication__JwtBearer__Authority=https://auth.tache.ai/realms/tache
    - Authentication__JwtBearer__Issuer=https://auth.tache.ai/realms/tache
    - Authentication__JwtBearer__Audience=hexalith-eventstore
    - Authentication__JwtBearer__RequireHttpsMetadata=true
    - ASPNETCORE_URLS=http://+:8080;
