---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: parties
  labels:
    app: parties
  annotations:
    dapr.io/enabled: 'true'
    dapr.io/config: accesscontrol-parties
    dapr.io/app-id: parties
    dapr.io/app-port: '8080'
    dapr.io/enable-api-logging: 'true'
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: parties
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: parties
      annotations:
        dapr.io/enabled: 'true'
        dapr.io/config: accesscontrol-parties
        dapr.io/app-id: parties
        dapr.io/app-port: '8080'
        dapr.io/enable-api-logging: 'true'
    spec:
      containers:
      - name: parties
        image: registry.hexalith.com/parties:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        envFrom:
        - configMapRef:
            name: parties-env
      terminationGracePeriodSeconds: 180