---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-blazor-ui
  labels:
    app: sample-blazor-ui
  annotations:
    dapr.io/enabled: "true"
    dapr.io/app-id: sample-blazor-ui
    dapr.io/enable-api-logging: 'true'
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: sample-blazor-ui
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sample-blazor-ui
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: sample-blazor-ui
        dapr.io/enable-api-logging: 'true'
    spec:
      imagePullSecrets:
      - name: zot-pull-secret
      containers:
      - name: sample-blazor-ui
        image: registry.hexalith.com/sample-blazor-ui:0.0.0-preview.0.506
        imagePullPolicy: IfNotPresent
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 10
          timeoutSeconds: 10
          periodSeconds: 10
          failureThreshold: 30
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 120
          timeoutSeconds: 10
          periodSeconds: 10
          failureThreshold: 30
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        env:
        - name: EventStore__Authentication__Username
          valueFrom:
            secretKeyRef:
              name: hexalith-tache-ui-credentials
              key: username
        - name: EventStore__Authentication__Password
          valueFrom:
            secretKeyRef:
              name: hexalith-tache-ui-credentials
              key: password
        - name: EventStore__Authentication__ClientSecret
          valueFrom:
            secretKeyRef:
              name: hexalith-eventstore-ui-oidc-client
              key: client-secret
              optional: true
        envFrom:
        - configMapRef:
            name: sample-blazor-ui-env
      terminationGracePeriodSeconds: 180
