---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventstore
  labels:
    app: eventstore
  annotations:
    dapr.io/enabled: 'true'
    dapr.io/config: accesscontrol
    dapr.io/app-id: eventstore
    dapr.io/app-port: '8080'
    dapr.io/enable-api-logging: 'true'
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: eventstore
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: eventstore
      annotations:
        dapr.io/enabled: 'true'
        dapr.io/config: accesscontrol
        dapr.io/app-id: eventstore
        dapr.io/app-port: '8080'
        dapr.io/enable-api-logging: 'true'
    spec:
      imagePullSecrets:
      - name: zot-pull-secret
      containers:
      - name: eventstore
        image: registry.hexalith.com/eventstore:0.0.0-preview.0.353
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
        envFrom:
        - configMapRef:
            name: eventstore-env
        volumeMounts:
        - name: domain-config
          mountPath: /app/appsettings.Production.json
          subPath: appsettings.Production.json
          readOnly: true
      volumes:
      - name: domain-config
        configMap:
          name: eventstore-domain-config
      terminationGracePeriodSeconds: 180