---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventstore
  labels:
    app: eventstore
  annotations:
    dapr.io/enabled: 'true'
    dapr.io/config: accesscontrol
    dapr.io/app-id: eventstore
    dapr.io/app-port: '8080'
    dapr.io/enable-api-logging: 'true'
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: eventstore
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: eventstore
      annotations:
        dapr.io/enabled: 'true'
        dapr.io/config: accesscontrol
        dapr.io/app-id: eventstore
        dapr.io/app-port: '8080'
        dapr.io/enable-api-logging: 'true'
    spec:
      containers:
      - name: eventstore
        image: registry.hexalith.com/eventstore:staging-latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        envFrom:
        - configMapRef:
            name: eventstore-env
      terminationGracePeriodSeconds: 180