resources:
- deployment.yaml
- service.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: eventstore-env
  literals:
    - OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY=in_memory
    - ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
    - HTTP_PORTS=8080
    - Authentication__DaprInternal__AllowedCallers__0=tenants
    - EventStore__DomainServices__Registrations__*|party|v1__AppId=parties
    - EventStore__DomainServices__Registrations__*|party|v1__MethodName=process
    - EventStore__DomainServices__Registrations__*|party|v1__TenantId=*
    - EventStore__DomainServices__Registrations__*|party|v1__Domain=party
    - EventStore__DomainServices__Registrations__*|party|v1__Version=v1
    - ASPNETCORE_URLS=http://+:8080;

