---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenants
  labels:
    app: tenants
  annotations:
    dapr.io/enabled: "true"
    dapr.io/config: accesscontrol-tenants
    dapr.io/app-id: tenants
    dapr.io/enable-api-logging: 'true'
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: tenants
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tenants
      annotations:
        dapr.io/app-port: '8080'
        dapr.io/enabled: "true"
        dapr.io/config: accesscontrol-tenants
        dapr.io/app-id: tenants
        dapr.io/enable-api-logging: 'true'
    spec:
      imagePullSecrets:
      - name: zot-pull-secret
      containers:
      - name: tenants
        image: registry.hexalith.com/tenants:0.0.0-preview.0.500
        imagePullPolicy: IfNotPresent
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 10
          timeoutSeconds: 10
          periodSeconds: 10
          failureThreshold: 30
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 120
          timeoutSeconds: 10
          periodSeconds: 10
          failureThreshold: 30
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        env:
        - name: Authentication__JwtBearer__SigningKey
          valueFrom:
            secretKeyRef:
              name: hexalith-jwt-signing
              key: value
        envFrom:
        - configMapRef:
            name: tenants-env
      terminationGracePeriodSeconds: 180