---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenants
  labels:
    app: tenants
  annotations:
    dapr.io/enabled: 'true'
    dapr.io/config: accesscontrol-tenants
    dapr.io/app-id: tenants
    dapr.io/app-port: '8080'
    dapr.io/enable-api-logging: 'true'
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: tenants
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tenants
      annotations:
        dapr.io/enabled: 'true'
        dapr.io/config: accesscontrol-tenants
        dapr.io/app-id: tenants
        dapr.io/app-port: '8080'
        dapr.io/enable-api-logging: 'true'
    spec:
      imagePullSecrets:
      - name: zot-pull-secret
      containers:
      - name: tenants
        image: registry.hexalith.com/tenants:0.0.0-preview.0.353
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        envFrom:
        - configMapRef:
            name: tenants-env
      terminationGracePeriodSeconds: 180