---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: parties-ui
  labels:
    app: parties-ui
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: parties-ui
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: parties-ui
    spec:
      hostAliases:
      - ip: 10.233.41.235
        hostnames:
        - auth.tache.ai
      imagePullSecrets:
      - name: zot-pull-secret
      containers:
      - name: parties-ui
        image: registry.hexalith.com/parties-ui:0.0.0-preview.0.506
        imagePullPolicy: IfNotPresent
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 10
          timeoutSeconds: 10
          periodSeconds: 10
          failureThreshold: 30
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 120
          timeoutSeconds: 10
          periodSeconds: 10
          failureThreshold: 30
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        env:
        - name: Authentication__OpenIdConnect__ClientSecret
          valueFrom:
            secretKeyRef:
              name: hexalith-parties-ui-oidc-client
              key: client-secret
        envFrom:
        - configMapRef:
            name: parties-ui-env
      terminationGracePeriodSeconds: 180
