---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventstore-admin-ui
  labels:
    app: eventstore-admin-ui
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: eventstore-admin-ui
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: eventstore-admin-ui
    spec:
      containers:
      - name: eventstore-admin-ui
        image: registry.hexalith.com/eventstore-admin-ui:0.1.1-preview.0.3
        imagePullPolicy: IfNotPresent
        readinessProbe:
          httpGet:
            path: /health
            port: http
        livenessProbe:
          httpGet:
            path: /health
            port: http
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        envFrom:
        - configMapRef:
            name: eventstore-admin-ui-env
      imagePullSecrets:
      - name: zot-pull-secret
      terminationGracePeriodSeconds: 180
