resources:
- deployment.yaml
- service.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: eventstore-admin-ui-env
  literals:
    - OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY=in_memory
    - ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
    - HTTP_PORTS=8080
    - EVENTSTORE_ADMIN_HTTP=http://eventstore-admin:8080
    - services__eventstore-admin__http__0=http://eventstore-admin:8080
    - EventStore__AdminServer__BaseUrl=http://eventstore-admin:8080
    - EventStore__AdminServer__SwaggerUrl=http://eventstore-admin:8080/swagger/index.html
    - EventStore__SignalR__HubUrl=http://eventstore:8080/hubs/projection-changes
    - ASPNETCORE_ENVIRONMENT=Development
    - DOTNET_ENVIRONMENT=Development
    - EventStore__Authentication__Authority=https://auth.tache.ai/realms/tache
    - EventStore__Authentication__Issuer=https://auth.tache.ai/realms/tache
    - EventStore__Authentication__Audience=hexalith-eventstore
    - EventStore__Authentication__ClientId=hexalith-eventstore
    - EventStore__Authentication__ClientCredentialsClientId=hexalith-eventstore-ui
    - ASPNETCORE_URLS=http://+:8080;
